import type {
  ArticleRecord,
  ProjectRecord,
  ToolRecord,
} from "@/lib/content/types";

export const demoTools: ToolRecord[] = [
  {
    id: "demo-pdf-merge",
    slug: "pdf-merge",
    name: { en: "PDF Merge", de: "PDFs zusammenführen" },
    summary: {
      en: "Combine multiple PDF files in your chosen order.",
      de: "Mehrere PDF-Dateien in der gewünschten Reihenfolge verbinden.",
    },
    description: {
      en: "Arrange and merge multiple PDF documents into one downloadable file entirely in your browser.",
      de: "Mehrere PDF-Dokumente sortieren und vollständig im Browser zu einer herunterladbaren Datei zusammenführen.",
    },
    category: "documents",
    icon: "pdf",
    featured: true,
    sortOrder: 0,
    usageCount: 0,
  },
  {
    id: "demo-pdf-split",
    slug: "pdf-split",
    name: { en: "PDF Split", de: "PDF teilen" },
    summary: {
      en: "Split one PDF into clearly defined page ranges.",
      de: "Eine PDF an festgelegten Seiten in mehrere Dateien teilen.",
    },
    description: {
      en: "Choose split points, preview every output range, and download the resulting PDF files as a ZIP archive without uploading the document.",
      de: "Trennstellen festlegen, alle Ausgabebereiche prüfen und die erzeugten PDF-Dateien ohne Upload als ZIP-Archiv herunterladen.",
    },
    category: "documents",
    icon: "pdf",
    featured: true,
    sortOrder: 1,
    usageCount: 0,
  },
  {
    id: "demo-pdf-compress",
    slug: "pdf-compress",
    name: { en: "Compress PDF", de: "PDF verkleinern" },
    summary: {
      en: "Reduce PDF file size while keeping the best possible quality.",
      de: "PDF-Dateigröße verringern und bestmögliche Qualität behalten.",
    },
    description: {
      en: "Reduce PDF file size with selectable quality levels and download the optimized document without uploading it.",
      de: "Die Dateigröße einer PDF mit wählbaren Qualitätsstufen verringern und das optimierte Dokument ohne Upload herunterladen.",
    },
    category: "documents",
    icon: "shrink",
    featured: true,
    sortOrder: 2,
    usageCount: 0,
  },
  {
    id: "demo-pdf-to-jpg",
    slug: "pdf-to-jpg",
    name: { en: "PDF to JPG", de: "PDF in JPG" },
    summary: {
      en: "Extract embedded images or convert every PDF page to JPG.",
      de: "Alle Bilder aus einer PDF-Datei extrahieren oder jede Seite in ein JPG-Bild konvertieren.",
    },
    description: {
      en: "Render every PDF page as a high-quality JPG or export embedded raster images directly in your browser without uploading the document.",
      de: "Jede PDF-Seite als hochwertiges JPG rendern oder eingebettete Rasterbilder direkt im Browser exportieren, ohne das Dokument hochzuladen.",
    },
    category: "documents",
    icon: "pdf-image",
    featured: true,
    sortOrder: 3,
    usageCount: 0,
  },
  {
    id: "demo-jpg-to-pdf",
    slug: "jpg-to-pdf",
    name: { en: "JPG to PDF", de: "JPG in PDF" },
    summary: {
      en: "Convert images to PDF and adjust orientation and margins.",
      de: "Konvertieren Sie Ihre Bilder in PDFs. Passen Sie dabei die Ausrichtung und die Ränder an.",
    },
    description: {
      en: "Arrange JPG images, choose page size, orientation, and margins, and create one downloadable PDF locally in your browser.",
      de: "JPG-Bilder sortieren, Seitengröße, Ausrichtung und Ränder festlegen und lokal im Browser eine herunterladbare PDF erstellen.",
    },
    category: "documents",
    icon: "image-pdf",
    featured: true,
    sortOrder: 4,
    usageCount: 0,
  },
  {
    id: "demo-pdf-rotate",
    slug: "pdf-rotate",
    name: { en: "Rotate PDF", de: "PDF drehen" },
    summary: {
      en: "Rotate individual pages or an entire PDF.",
      de: "Einzelne Seiten oder eine ganze PDF drehen.",
    },
    description: {
      en: "Preview and rotate individual PDF pages or the complete document locally in your browser without changing document quality.",
      de: "Einzelne PDF-Seiten oder das gesamte Dokument in der Vorschau drehen und lokal im Browser ohne Qualitätsverlust speichern.",
    },
    category: "documents",
    icon: "rotate",
    featured: false,
    sortOrder: 5,
    usageCount: 0,
  },
  {
    id: "demo-pdf-organize",
    slug: "pdf-organize",
    name: { en: "Organize PDF", de: "PDF organisieren" },
    summary: {
      en: "Reorder, rotate, and remove PDF pages.",
      de: "PDF-Seiten sortieren, drehen und entfernen.",
    },
    description: {
      en: "Arrange PDF pages in a new order, correct their orientation, remove unneeded pages, and create a clean document entirely in your browser.",
      de: "PDF-Seiten neu anordnen, ihre Ausrichtung korrigieren, überflüssige Seiten entfernen und vollständig im Browser ein neues Dokument erzeugen.",
    },
    category: "documents",
    icon: "organize",
    featured: false,
    sortOrder: 6,
    usageCount: 0,
  },
  {
    id: "demo-pdf-page-numbers",
    slug: "pdf-page-numbers",
    name: { en: "Add PDF Page Numbers", de: "PDF-Seitenzahlen" },
    summary: {
      en: "Add page numbers with a custom format and position.",
      de: "Seitenzahlen mit eigenem Format und eigener Position einfügen.",
    },
    description: {
      en: "Add page numbers to a chosen PDF page range, select their format and position, and download the numbered document without uploading it.",
      de: "Seitenzahlen in einen gewählten PDF-Bereich einfügen, Format und Position festlegen und das nummerierte Dokument ohne Upload herunterladen.",
    },
    category: "documents",
    icon: "page-numbers",
    featured: false,
    sortOrder: 7,
    usageCount: 0,
  },
  {
    id: "demo-image-to-jpg",
    slug: "image-to-jpg",
    name: { en: "Image to JPG", de: "Bild in JPG" },
    summary: {
      en: "Convert PNG, WebP, or JPG images to compact JPG files.",
      de: "PNG-, WebP- oder JPG-Bilder in kompakte JPG-Dateien umwandeln.",
    },
    description: {
      en: "Convert JPG, PNG, and WebP images to downloadable JPG files locally in your browser, with selectable output quality.",
      de: "JPG-, PNG- und WebP-Bilder lokal im Browser mit wählbarer Ausgabequalität in herunterladbare JPG-Dateien konvertieren.",
    },
    category: "images",
    icon: "image",
    featured: false,
    sortOrder: 0,
    usageCount: 0,
  },
  {
    id: "demo-image-to-png",
    slug: "image-to-png",
    name: { en: "Image to PNG", de: "Bild in PNG" },
    summary: {
      en: "Convert JPG, WebP, or PNG images to lossless PNG files.",
      de: "JPG-, WebP- oder PNG-Bilder in verlustfreie PNG-Dateien umwandeln.",
    },
    description: {
      en: "Convert JPG, PNG, and WebP images to downloadable PNG files locally in your browser while preserving transparency.",
      de: "JPG-, PNG- und WebP-Bilder lokal im Browser in herunterladbare PNG-Dateien konvertieren und Transparenz erhalten.",
    },
    category: "images",
    icon: "image",
    featured: false,
    sortOrder: 1,
    usageCount: 0,
  },
  {
    id: "demo-image-to-webp",
    slug: "image-to-webp",
    name: { en: "Image to WebP", de: "Bild in WebP" },
    summary: {
      en: "Convert JPG, PNG, or WebP images to efficient WebP files.",
      de: "JPG-, PNG- oder WebP-Bilder in effiziente WebP-Dateien umwandeln.",
    },
    description: {
      en: "Convert JPG, PNG, and WebP images to downloadable WebP files locally in your browser, with selectable output quality.",
      de: "JPG-, PNG- und WebP-Bilder lokal im Browser mit wählbarer Ausgabequalität in herunterladbare WebP-Dateien konvertieren.",
    },
    category: "images",
    icon: "image",
    featured: false,
    sortOrder: 2,
    usageCount: 0,
  },
  {
    id: "demo-image-rotate",
    slug: "image-rotate",
    name: { en: "Rotate images", de: "Bild drehen" },
    summary: {
      en: "Rotate multiple JPG, PNG, or GIF images at once. Choose all images or only landscape or portrait images.",
      de: "Mehrere JPG-, PNG- oder GIF-Bilder gleichzeitig drehen. Wahlweise alle oder nur Bilder im Quer- oder Hochformat drehen.",
    },
    description: {
      en: "Rotate images locally by 90°, 180°, or 270°, preview the result, and download individual files or a ZIP. GIF animations are preserved.",
      de: "Bilder lokal um 90°, 180° oder 270° drehen, das Ergebnis vorab ansehen und einzeln oder als ZIP herunterladen. GIF-Animationen bleiben erhalten.",
    },
    category: "images",
    icon: "rotate",
    featured: false,
    sortOrder: 3,
    usageCount: 0,
  },
  {
    id: "demo-excel-to-csv",
    slug: "excel-to-csv",
    name: { en: "Excel to CSV", de: "Excel zu CSV" },
    summary: {
      en: "Export any worksheet as a clean CSV file.",
      de: "Beliebige Tabellenblätter als saubere CSV-Datei exportieren.",
    },
    description: {
      en: "Open an XLSX workbook, choose a worksheet, preview its data, and export it as CSV without uploading the file.",
      de: "Eine XLSX-Arbeitsmappe öffnen, ein Tabellenblatt auswählen, die Daten prüfen und ohne Upload als CSV exportieren.",
    },
    category: "office",
    icon: "spreadsheet",
    featured: false,
    sortOrder: 2,
    usageCount: 0,
  },
  {
    id: "demo-csv-to-excel",
    slug: "csv-to-excel",
    name: { en: "CSV to Excel", de: "CSV zu Excel" },
    summary: {
      en: "Turn CSV and TSV tables into polished Excel workbooks.",
      de: "CSV- und TSV-Tabellen in übersichtliche Excel-Dateien umwandeln.",
    },
    description: {
      en: "Open a CSV or TSV file, check its delimiter and columns, and create a formatted XLSX workbook without uploading the data.",
      de: "Eine CSV- oder TSV-Datei öffnen, Trennzeichen und Spalten prüfen und ohne Upload eine formatierte XLSX-Arbeitsmappe erstellen.",
    },
    category: "office",
    icon: "spreadsheet",
    featured: false,
    sortOrder: 3,
    usageCount: 0,
  },
  {
    id: "demo-word-to-pdf",
    slug: "word-to-pdf",
    name: { en: "Word to PDF", de: "Word in PDF" },
    summary: {
      en: "Convert DOC and DOCX files into easy-to-share PDFs.",
      de: "Machen Sie DOC- und DOCX-Dateien einfacher lesbar, indem Sie sie in PDFs umwandeln.",
    },
    description: {
      en: "Convert DOC and DOCX documents into PDF files directly in your browser. DOCX layouts are retained where possible, while older DOC files become clean text documents.",
      de: "DOC- und DOCX-Dokumente direkt im Browser in PDF-Dateien umwandeln. DOCX-Layouts werden bestmöglich erhalten; ältere DOC-Dateien werden als übersichtliches Textdokument ausgegeben.",
    },
    category: "office",
    icon: "word-pdf",
    featured: false,
    sortOrder: 4,
    usageCount: 0,
  },
  {
    id: "demo-json-formatter",
    slug: "json-formatter",
    name: { en: "JSON Formatter", de: "JSON-Formatierer" },
    summary: {
      en: "Format, validate, and inspect JSON.",
      de: "JSON formatieren, validieren und prüfen.",
    },
    description: {
      en: "Turn compact or inconsistent JSON into readable, validated output without sending data to a server.",
      de: "Kompaktes oder uneinheitliches JSON lesbar formatieren und validieren, ohne Daten an einen Server zu senden.",
    },
    category: "formatters",
    icon: "braces",
    featured: true,
    sortOrder: 2,
    usageCount: 0,
  },
  {
    id: "demo-base64",
    slug: "base64",
    name: { en: "Base64 Encoder", de: "Base64-Konverter" },
    summary: {
      en: "Encode and decode Base64 text.",
      de: "Base64-Text kodieren und dekodieren.",
    },
    description: {
      en: "Convert UTF-8 text to Base64 and back entirely in your browser.",
      de: "UTF-8-Text vollständig im Browser in Base64 umwandeln und zurück.",
    },
    category: "encoders",
    icon: "binary",
    featured: true,
    sortOrder: 3,
    usageCount: 0,
  },
  {
    id: "demo-uuid",
    slug: "uuid-generator",
    name: { en: "UUID Generator", de: "UUID-Generator" },
    summary: {
      en: "Generate secure UUID v4 values.",
      de: "Sichere UUID-v4-Werte erzeugen.",
    },
    description: {
      en: "Generate one or many RFC 4122 UUID v4 identifiers using the browser crypto API.",
      de: "Eine oder mehrere RFC-4122-UUIDs v4 mit der Crypto-API des Browsers erzeugen.",
    },
    category: "generators",
    icon: "fingerprint",
    featured: true,
    sortOrder: 4,
    usageCount: 0,
  },
  {
    id: "demo-url-codec",
    slug: "url-encoder",
    name: { en: "URL Encoder", de: "URL-Kodierer" },
    summary: {
      en: "Encode and decode URL components.",
      de: "URL-Bestandteile kodieren und dekodieren.",
    },
    description: {
      en: "Safely encode or decode query values and URL path fragments.",
      de: "Query-Werte und URL-Pfadbestandteile sicher kodieren oder dekodieren.",
    },
    category: "encoders",
    icon: "link",
    featured: false,
    sortOrder: 5,
    usageCount: 0,
  },
  {
    id: "demo-hash-generator",
    slug: "hash-generator",
    name: { en: "SHA-256 Generator", de: "SHA-256-Generator" },
    summary: {
      en: "Create a SHA-256 hash from text.",
      de: "SHA-256-Hash aus Text erzeugen.",
    },
    description: {
      en: "Generate a deterministic SHA-256 digest from UTF-8 text using the browser crypto API.",
      de: "Einen deterministischen SHA-256-Hash aus UTF-8-Text mit der Crypto-API des Browsers erzeugen.",
    },
    category: "generators",
    icon: "hash",
    featured: true,
    sortOrder: 6,
    usageCount: 0,
  },
  {
    id: "demo-timestamp",
    slug: "timestamp-converter",
    name: { en: "Timestamp Converter", de: "Zeitstempel-Konverter" },
    summary: {
      en: "Convert dates and Unix timestamps.",
      de: "Datum und Unix-Zeitstempel konvertieren.",
    },
    description: {
      en: "Convert an ISO date or Unix timestamp into readable UTC and epoch values.",
      de: "ISO-Datum oder Unix-Zeitstempel in lesbare UTC- und Epoch-Werte umwandeln.",
    },
    category: "converters",
    icon: "clock",
    featured: true,
    sortOrder: 7,
    usageCount: 0,
  },
  {
    id: "demo-case-converter",
    slug: "case-converter",
    name: { en: "Case Converter", de: "Groß-/Kleinschreibung" },
    summary: {
      en: "Transform text casing instantly.",
      de: "Textschreibweise direkt ändern.",
    },
    description: {
      en: "Convert text to uppercase, lowercase, or title case without leaving the browser.",
      de: "Text direkt im Browser in Groß-, Klein- oder Titelschreibung umwandeln.",
    },
    category: "formatters",
    icon: "case",
    featured: false,
    sortOrder: 8,
    usageCount: 0,
  },
  {
    id: "demo-color-converter",
    slug: "color-converter",
    name: { en: "Color Converter", de: "Farbkonverter" },
    summary: {
      en: "Convert HEX colors to RGB.",
      de: "HEX-Farben in RGB umwandeln.",
    },
    description: {
      en: "Validate a three- or six-digit HEX color and convert it to RGB values.",
      de: "Drei- oder sechsstellige HEX-Farben validieren und in RGB-Werte umwandeln.",
    },
    category: "converters",
    icon: "palette",
    featured: false,
    sortOrder: 9,
    usageCount: 0,
  },
  {
    id: "demo-word-counter",
    slug: "word-counter",
    name: { en: "Word Counter", de: "Wortzähler" },
    summary: {
      en: "Count words, characters, and lines.",
      de: "Wörter, Zeichen und Zeilen zählen.",
    },
    description: {
      en: "Inspect word, character, and line counts for any pasted text locally.",
      de: "Wort-, Zeichen- und Zeilenanzahl für beliebigen Text lokal ermitteln.",
    },
    category: "text",
    icon: "list",
    featured: false,
    sortOrder: 10,
    usageCount: 0,
  },
  {
    id: "demo-slug-generator",
    slug: "slug-generator",
    name: { en: "Slug Generator", de: "Slug-Generator" },
    summary: {
      en: "Turn text into a clean URL slug.",
      de: "Text in einen sauberen URL-Slug umwandeln.",
    },
    description: {
      en: "Normalize text into a lowercase, URL-friendly slug with predictable separators.",
      de: "Text in einen kleingeschriebenen, URL-freundlichen Slug mit einheitlichen Trennzeichen umwandeln.",
    },
    category: "generators",
    icon: "wand",
    featured: false,
    sortOrder: 11,
    usageCount: 0,
  },
];

export const demoArticles: ArticleRecord[] = [
  {
    id: "demo-useful-tools",
    slug: "designing-tools-that-earn-their-tab",
    title: {
      en: "Designing tools that earn their tab",
      de: "Tools entwickeln, die ihren Tab verdienen",
    },
    excerpt: {
      en: "A practical framework for building focused utilities people return to.",
      de: "Ein praktischer Rahmen für fokussierte Werkzeuge, zu denen Menschen zurückkehren.",
    },
    content: {
      en: "## Start with one finished job\n\nA useful tool has a narrow promise and a complete path from input to result. The interface should expose that path immediately.\n\n## Keep data close\n\nWhen a task can run safely in the browser, local processing improves speed, privacy, and resilience.\n\n> This sample article demonstrates the bilingual publishing model and should be replaced or approved before launch.",
      de: "## Mit einer abgeschlossenen Aufgabe beginnen\n\nEin nützliches Tool hat ein enges Versprechen und einen vollständigen Weg von der Eingabe zum Ergebnis. Die Oberfläche sollte diesen Weg sofort zeigen.\n\n## Daten lokal halten\n\nWenn eine Aufgabe sicher im Browser laufen kann, verbessert lokale Verarbeitung Geschwindigkeit, Datenschutz und Robustheit.\n\n> Dieser Beispielartikel demonstriert das zweisprachige Publikationsmodell und sollte vor dem Launch ersetzt oder freigegeben werden.",
    },
    publishedAt: new Date("2026-08-12T09:00:00.000Z"),
    isDemo: true,
  },
  {
    id: "demo-apis",
    slug: "reliable-api-boundaries",
    title: { en: "Reliable API boundaries", de: "Verlässliche API-Grenzen" },
    excerpt: {
      en: "Why validation, explicit failure states, and idempotency belong at the boundary.",
      de: "Warum Validierung, klare Fehlerzustände und Idempotenz an die Systemgrenze gehören.",
    },
    content: {
      en: "## Boundaries carry responsibility\n\nAn API boundary should turn ambiguous input into explicit domain state. Validation errors are part of the contract, not an afterthought.\n\n> This is sample editorial content for the initial site build.",
      de: "## Grenzen tragen Verantwortung\n\nEine API-Grenze sollte mehrdeutige Eingaben in expliziten Domänenzustand übersetzen. Validierungsfehler sind Teil des Vertrags.\n\n> Dies ist ein Beispielinhalt für den initialen Website-Aufbau.",
    },
    publishedAt: new Date("2026-07-24T09:00:00.000Z"),
    isDemo: true,
  },
];

export const demoProjects: ProjectRecord[] = [
  {
    id: "demo-tool-platform",
    slug: "tool-platform",
    title: "fcullmann.com Tools",
    summary: {
      en: "A bilingual platform for focused browser utilities and technical writing.",
      de: "Eine zweisprachige Plattform für fokussierte Browser-Tools und technische Artikel.",
    },
    description: {
      en: "The platform shown here is the first verified project record. Additional work will be added with source links and accurate context.",
      de: "Die hier gezeigte Plattform ist der erste verifizierte Projekteintrag. Weitere Arbeiten folgen mit Quelllinks und korrektem Kontext.",
    },
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Prisma"],
    isDemo: false,
  },
];
