INSERT INTO "Tool" (
  "id",
  "slug",
  "nameEn",
  "nameDe",
  "summaryEn",
  "summaryDe",
  "descriptionEn",
  "descriptionDe",
  "category",
  "icon",
  "status",
  "featured",
  "sortOrder",
  "usageCount",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'tool-image-to-jpg',
    'image-to-jpg',
    'Image to JPG',
    'Bild in JPG',
    'Convert PNG, WebP, or JPG images to compact JPG files.',
    'PNG-, WebP- oder JPG-Bilder in kompakte JPG-Dateien umwandeln.',
    'Convert JPG, PNG, and WebP images to downloadable JPG files locally in your browser, with selectable output quality.',
    'JPG-, PNG- und WebP-Bilder lokal im Browser mit wählbarer Ausgabequalität in herunterladbare JPG-Dateien konvertieren.',
    'images',
    'image',
    'PUBLISHED',
    false,
    0,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'tool-image-to-png',
    'image-to-png',
    'Image to PNG',
    'Bild in PNG',
    'Convert JPG, WebP, or PNG images to lossless PNG files.',
    'JPG-, WebP- oder PNG-Bilder in verlustfreie PNG-Dateien umwandeln.',
    'Convert JPG, PNG, and WebP images to downloadable PNG files locally in your browser while preserving transparency.',
    'JPG-, PNG- und WebP-Bilder lokal im Browser in herunterladbare PNG-Dateien konvertieren und Transparenz erhalten.',
    'images',
    'image',
    'PUBLISHED',
    false,
    1,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'tool-image-to-webp',
    'image-to-webp',
    'Image to WebP',
    'Bild in WebP',
    'Convert JPG, PNG, or WebP images to efficient WebP files.',
    'JPG-, PNG- oder WebP-Bilder in effiziente WebP-Dateien umwandeln.',
    'Convert JPG, PNG, and WebP images to downloadable WebP files locally in your browser, with selectable output quality.',
    'JPG-, PNG- und WebP-Bilder lokal im Browser mit wählbarer Ausgabequalität in herunterladbare WebP-Dateien konvertieren.',
    'images',
    'image',
    'PUBLISHED',
    false,
    2,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("slug") DO NOTHING;
