INSERT INTO "Tool" (
  "id",
  "slug",
  "nameEn",
  "nameDe",
  "summaryEn",
  "summaryDe",
  "descriptionEn",
  "descriptionDe",
  "category",
  "icon",
  "status",
  "featured",
  "sortOrder",
  "usageCount",
  "createdAt",
  "updatedAt"
)
VALUES
  (
    'tool-pdf-rotate',
    'pdf-rotate',
    'Rotate PDF',
    'PDF drehen',
    'Rotate individual pages or an entire PDF.',
    'Einzelne Seiten oder eine ganze PDF drehen.',
    'Preview and rotate individual PDF pages or the complete document locally in your browser without changing document quality.',
    'Einzelne PDF-Seiten oder das gesamte Dokument in der Vorschau drehen und lokal im Browser ohne Qualitätsverlust speichern.',
    'documents',
    'rotate',
    'PUBLISHED',
    false,
    5,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'tool-pdf-organize',
    'pdf-organize',
    'Organize PDF',
    'PDF organisieren',
    'Reorder, rotate, and remove PDF pages.',
    'PDF-Seiten sortieren, drehen und entfernen.',
    'Arrange PDF pages in a new order, correct their orientation, remove unneeded pages, and create a clean document entirely in your browser.',
    'PDF-Seiten neu anordnen, ihre Ausrichtung korrigieren, überflüssige Seiten entfernen und vollständig im Browser ein neues Dokument erzeugen.',
    'documents',
    'organize',
    'PUBLISHED',
    false,
    6,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'tool-pdf-page-numbers',
    'pdf-page-numbers',
    'Add PDF Page Numbers',
    'PDF-Seitenzahlen',
    'Add page numbers with a custom format and position.',
    'Seitenzahlen mit eigenem Format und eigener Position einfügen.',
    'Add page numbers to a chosen PDF page range, select their format and position, and download the numbered document without uploading it.',
    'Seitenzahlen in einen gewählten PDF-Bereich einfügen, Format und Position festlegen und das nummerierte Dokument ohne Upload herunterladen.',
    'documents',
    'page-numbers',
    'PUBLISHED',
    false,
    7,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("slug") DO NOTHING;
