# KeyHelp: tools.fcullmann.com -> additional Apache directives for HTTPS.
ProxyRequests Off
ProxyPreserveHost On
ProxyAddHeaders On
RequestHeader unset Forwarded
RequestHeader unset X-Forwarded-For
RequestHeader unset X-Forwarded-Host
RequestHeader unset X-Forwarded-Server
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"
ProxyPass "/.well-known/acme-challenge/" "!"
ProxyPass "/" "http://127.0.0.1:3009/" connectiontimeout=5 timeout=120
ProxyPassReverse "/" "http://127.0.0.1:3009/"
